INSERT INTO movie (title) VALUES ('The Shawshank Redemption');
INSERT INTO movie (title) VALUES ('The Godfather');
INSERT INTO movie (title) VALUES ('The Dark Knight');
INSERT INTO movie (title) VALUES ('The Godfather Part II');
INSERT INTO movie (title) VALUES ('The Lord of the Rings: The Return of the King');
INSERT INTO movie (title) VALUES ('Schindlers List');
INSERT INTO movie (title) VALUES ('Pulp Fiction');
INSERT INTO movie (title) VALUES ('The Lord of The Rings: The Fellowship of the Ring');
INSERT INTO movie (title) VALUES ('Forrest Gump');
INSERT INTO movie (title) VALUES ('The Lord of the Rings: The Two Towers');
INSERT INTO movie (title) VALUES ('Fight Club');
INSERT INTO movie (title) VALUES ('Inception');
INSERT INTO movie (title) VALUES ('Star Wars: Episode V - The Empire Strikes Back');
INSERT INTO movie (title) VALUES ('The Matrix');
INSERT INTO movie (title) VALUES ('Goodfellas');
INSERT INTO movie (title) VALUES ('Interstellar');
INSERT INTO movie (title) VALUES ('Se7en');
INSERT INTO movie (title) VALUES ('The Silence of the Lambs');
INSERT INTO movie (title) VALUES ('Saving Private Ryan');
INSERT INTO movie (title) VALUES ('City of God');
INSERT INTO movie (title) VALUES ('Life Is Beautiful');
INSERT INTO movie (title) VALUES ('The Green Mile');
INSERT INTO movie (title) VALUES ('Terminator 2: Judgment Day');
INSERT INTO movie (title) VALUES ('Star Wars: Episode IV - A New Hope');
INSERT INTO movie (title) VALUES ('Back to the Future');
INSERT INTO movie (title) VALUES ('Spirited Away');
INSERT INTO movie (title) VALUES ('The Pianist');
INSERT INTO movie (title) VALUES ('Parasite');
INSERT INTO movie (title) VALUES ('Gladiator');
INSERT INTO movie (title) VALUES ('The Lion King');
INSERT INTO movie (title) VALUES ('Spider-Man: Across the Spider-Verse');
INSERT INTO movie (title) VALUES ('The Departed');
INSERT INTO movie (title) VALUES ('Whiplash');
INSERT INTO movie (title) VALUES ('Grave of the Fireflies');
INSERT INTO movie (title) VALUES ('American History X');
INSERT INTO movie (title) VALUES ('Léon: The Professional');
INSERT INTO movie (title) VALUES ('The Prestige');
INSERT INTO movie (title) VALUES ('The Usual Suspects');
INSERT INTO movie (title) VALUES ('Dune: Part Two');
INSERT INTO movie (title) VALUES ('The Intouchables');
INSERT INTO movie (title) VALUES ('Alien');
INSERT INTO movie (title) VALUES ('Django Unchained');
INSERT INTO movie (title) VALUES ('Memento');
INSERT INTO movie (title) VALUES ('WALL-E');
INSERT INTO movie (title) VALUES ('Raiders of the Lost Ark');
INSERT INTO movie (title) VALUES ('The Lives of Others');
INSERT INTO movie (title) VALUES ('12th Fail');
INSERT INTO movie (title) VALUES ('Avengers: Infinity War');
INSERT INTO movie (title) VALUES ('Spider-Man: Into the Spider-Verse');
INSERT INTO movie (title) VALUES ('The Shining');
INSERT INTO movie (title) VALUES ('Aliens');
INSERT INTO movie (title) VALUES ('Inglorious Basterds');
INSERT INTO movie (title) VALUES ('The Dark Knight Rises');
INSERT INTO movie (title) VALUES ('Coco');
INSERT INTO movie (title) VALUES ('Toy Story');
INSERT INTO movie (title) VALUES ('Oldboy');
INSERT INTO movie (title) VALUES ('American Beauty');
INSERT INTO movie (title) VALUES ('Avengers: Endgame');
INSERT INTO movie (title) VALUES ('Das Boot');
INSERT INTO movie (title) VALUES ('Braveheart');
INSERT INTO movie (title) VALUES ('Good Will Hunting');
INSERT INTO movie (title) VALUES ('Princess Monoke');
INSERT INTO movie (title) VALUES ('Your Name.');
INSERT INTO movie (title) VALUES ('Joker');
INSERT INTO movie (title) VALUES ('3 Idiots');
INSERT INTO movie (title) VALUES ('Toy Story 3');
INSERT INTO movie (title) VALUES ('Star Wars: Episode VI - Return of the Jedi');
INSERT INTO movie (title) VALUES ('The Hunt');
INSERT INTO movie (title) VALUES ('Eternal Sunshine of the Spotless Mind');
INSERT INTO movie (title) VALUES ('Reservoir Dogs');
INSERT INTO movie (title) VALUES ('Scarface');
INSERT INTO movie (title) VALUES ('Oppenheimer');
INSERT INTO movie (title) VALUES ('Heat');
INSERT INTO movie (title) VALUES ('Full Metal Jacket');
INSERT INTO movie (title) VALUES ('Amélie');
INSERT INTO movie (title) VALUES ('Up');
INSERT INTO movie (title) VALUES ('Die Hard');
INSERT INTO movie (title) VALUES ('Indiana Jones and the Last Crusade');
INSERT INTO movie (title) VALUES ('Snatch');
INSERT INTO movie (title) VALUES ('1917');
INSERT INTO movie (title) VALUES ('L.A. Confidential');
INSERT INTO movie (title) VALUES ('Downfall');
INSERT INTO movie (title) VALUES ('Hamilton');
INSERT INTO movie (title) VALUES ('Taxi Driver');
INSERT INTO movie (title) VALUES ('Batman Begins');
INSERT INTO movie (title) VALUES ('The Wolf of Wall Street');
INSERT INTO movie (title) VALUES ('The Big Short');
INSERT INTO movie (title) VALUES ('Shutter Island');
INSERT INTO movie (title) VALUES ('Green Book');
INSERT INTO movie (title) VALUES ('The Truman Show');
INSERT INTO movie (title) VALUES ('The Father');
INSERT INTO movie (title) VALUES ('There Will Be Blood');
INSERT INTO movie (title) VALUES ('Jurassic Park');
INSERT INTO movie (title) VALUES ('Casino');
INSERT INTO movie (title) VALUES ('Top Gun: Maverick');
INSERT INTO movie (title) VALUES ('The Sixth Sense');
INSERT INTO movie (title) VALUES ('A Beautiful Mind');
INSERT INTO movie (title) VALUES ('Kill Bill: Vol. 1');
INSERT INTO movie (title) VALUES ('Finding Nemo');
INSERT INTO movie (title) VALUES ('Howls Moving Castle');
INSERT INTO movie (title) VALUES ('V for Vendetta');
INSERT INTO movie (title) VALUES ('Catch Me If You Can');
INSERT INTO movie (title) VALUES ('Spider-Man: No Way Home');
INSERT INTO movie (title) VALUES ('Harry Potter and the Deathly Hallows: Part 2');
INSERT INTO movie (title) VALUES ('Mad Max: Fury Road');
INSERT INTO movie (title) VALUES ('Blade Runner');
INSERT INTO movie (title) VALUES ('Monsters, Inc.');
INSERT INTO movie (title) VALUES ('Ratatouille');
INSERT INTO movie (title) VALUES ('Jaws');
INSERT INTO movie (title) VALUES ('Ford v Ferrari');
INSERT INTO movie (title) VALUES ('Logan');
INSERT INTO movie (title) VALUES ('The Terminator');
INSERT INTO movie (title) VALUES ('Rush');
INSERT INTO movie (title) VALUES ('The Social Network');
INSERT INTO movie (title) VALUES ('Groundhog Day');
INSERT INTO movie (title) VALUES ('');